### ISSUE TITLE
Generating POJO from introspection result not working

### ISSUE THREAD

**Issue by klvnnsrikanth** [kobylynskyi/graphql-java-codegen#1457]
## Issue Description

Hi I was able to generate an introspection result using the query from [here](https://gist.githubusercontent.com/craigbeck/b90915d49fda19d5b2b17ead14dcd6da/raw/e50819812a7a8a95b303ac0ea1464e2679e3e4bc/introspection-query.graphql) and use the result from my graphql service to generate client POJOs and client code.

I see the following error
```java
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at graphql.introspection.IntrospectionResultToSchema.createDeprecatedDirective(IntrospectionResultToSchema.java:310)
        at graphql.introspection.IntrospectionResultToSchema.createFields(IntrospectionResultToSchema.java:298)
        at graphql.introspection.IntrospectionResultToSchema.createObject(IntrospectionResultToSchema.java:286)
        at graphql.introspection.IntrospectionResultToSchema.createTypeDefinition(IntrospectionResultToSchema.java:171)
        at graphql.introspection.IntrospectionResultToSchema.createSchemaDefinition(IntrospectionResultToSchema.java:110)
 ``` 
I am not even sure what the issue is, but when I use the sample introspection result from the sample provided it works fine, but is there some issue with my introspection result? I cannot seem to understand what is wrong actually, can you help me with some pointers?

## Your Environment and Setup

* **graphql-java-codegen version**: *5.9.0*
* **Build tool**: *Gradle*

**Comment by klvnnsrikanth** [comment]
Ignore this, after upgrading to 5.10.0 version it seems to work.
