### ISSUE TITLE
[toString() Stackoverflow due to inner reference] (Version: [graphql-java-codegen 4.0.1])

### ISSUE THREAD

**Issue by JBrVJxsc** [kobylynskyi/graphql-java-codegen#431]
## Issue Description

I have two models, Child, and Parent.

Parent has a `child` field, and Child has a `parent` field, both point to each other.

When calling toString, it will throw the following exception:

`Exception in thread "main" java.lang.StackOverflowError
	at java.lang.StringBuilder.append(StringBuilder.java:208)
	at java.time.LocalDate.toString(LocalDate.java:2032)
	at java.time.LocalDateTime.toString(LocalDateTime.java:1972)
	at java.time.ZonedDateTime.toString(ZonedDateTime.java:2206)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:271)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at Element.toString(Element.java:281)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:149)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:137)
	at com.kobylynskyi.graphql.codegen.model.graphql.GraphQLRequestSerializer.getEntry(GraphQLRequestSerializer.java:127)
	at ElementType.toString(ElementType.java:270)`

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 4.0.1*
* **Build tool**: *E.g.: Gradle*
* **Java tool**: *E.g.: Oracle 8u241*
* **Mapping Config**: *E.g.:* 

```xml
<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
@JBrVJxsc, it's a good catch.
Do you have some expectations on how it should work in such scenarios?
btw, if you don't need `toString()`, you can disable it using: `<generateToString>false</generateToString>`

**Comment by JBrVJxsc** [comment]
TBH I don't know what should be a better way to express such a nested situation...   😄 

But you are right, I'm going to just disable the toString generation.

**Comment by jxnu-liguobin** [comment]
🤪 Maybe it should be defined as a self dependent type rather than two different types of interdependence? Such as 
```
type Filter @filterName {
    key: String
    op: String
    name: String
    values: [String] @fetch(from: "valuesList")
    exprs: [Filter] @fetch(from: "exprsList") # The exprs of the child may be empty.
    valueType: String  # The exprs of the parent may be empty.
}
```

**Comment by kobylynskyi** [comment]
Relevant to rzwitserloot/lombok#2255
