### ISSUE TITLE
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.5.3

### ISSUE THREAD

**Issue by donbeave** [kobylynskyi/graphql-java-codegen#601]
## Issue Description

Trying to use the Gradle plugin in one of my project, created a separate module for GraphQL codegen. Everytime when I run `graphqlCodegen` it's fail with an error:

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.5.3

Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with UUID 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).
        at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:153)
        at graphql.parser.antlr.GraphqlLexer.<clinit>(GraphqlLexer.java:276)

```

## Steps to Reproduce

1. `git clone git@github.com:expatiat/dumper.git`
2. `cd dumper/dumper-api-interface`
3. `../gradlew clean graphqlCodegen --info --stacktrace`

## Your Environment and Setup

* **graphql-java-codegen version**: *4.1.5*
* **Build tool**: *Gradle 6.8.3*
* **Mapping Config**: *E.g.:*

```kotlin
plugins {
    `java-library`
    id("io.github.kobylynskyi.graphql.codegen") version "4.1.5"
}

tasks.named<io.github.kobylynskyi.graphql.codegen.gradle.GraphQLCodegenGradleTask>("graphqlCodegen") {
    graphqlSchemaPaths = listOf(
        "$projectDir/../dumper-api/src/main/resources/graphql/dumper.graphqls",
        "$projectDir/../dumper-api/src/main/resources/graphql/include/dumper-enums.graphqls",
        "$projectDir/../dumper-api/src/main/resources/graphql/include/dumper-errors.graphqls",
        "$projectDir/../dumper-api/src/main/resources/graphql/include/dumper-inputs.graphqls",
        "$projectDir/../dumper-api/src/main/resources/graphql/include/dumper-payloads.graphqls",
        "$projectDir/../dumper-api/src/main/resources/graphql/include/dumper-types.graphqls"
    )
    outputDir = File("$buildDir/generated")
    packageName = "com.example.graphql.model"
}

sourceSets {
    getByName("main").java.srcDirs("$buildDir/generated")
}

tasks.named<JavaCompile>("compileJava") {
    dependsOn("graphqlCodegen")
}
```

**Comment by kobylynskyi** [comment]
@donbeave perhaps this is because in your repository you are using graphql-java-tools of version 11.0.0:
https://github.com/expatiat/dumper/blob/60d188e908c28b966b9c47560b1b10760be101fa/buildSrc/src/main/java/Versions.kt#L62

And graphql-java-tools-11.0.0 uses graphql-java-**16.1**:
https://github.com/graphql-java-kickstart/graphql-java-tools/releases/tag/11.0.0

graphql-java-codegen is still on version 15 and was not yet upgraded to 16.

I assume the error will go away once graphql-java-codegen will upgrade its dependency of graphql-java to 16.1.

**Comment by donbeave** [comment]
@kobylynskyi Seems it's not because of this. Here is a reason why I think it's not this case,

1) the Gradle submodule `dumper-api-interface` don't have any graphql related dependencies, here is a report for this module:

```bash
~/Projects/dumper/dumper-api-interface main ❯ ../gradlew dependencies

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

> Task :dumper-api-interface:dependencies

------------------------------------------------------------
Project ':dumper-api-interface'
------------------------------------------------------------

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

api - API dependencies for source set 'main'. (n)
No dependencies

apiElements - API elements for main. (n)
No dependencies

archives - Configuration for archive artifacts. (n)
No dependencies

compileClasspath - Compile classpath for source set 'main'.
\--- com.github.spotbugs:spotbugs-annotations:4.2.0
     \--- com.google.code.findbugs:jsr305:3.0.2

compileOnly - Compile only dependencies for source set 'main'. (n)
No dependencies

compileOnlyApi - Compile only API dependencies for source set 'main'. (n)
No dependencies

default - Configuration for default artifacts. (n)
No dependencies

implementation - Implementation only dependencies for source set 'main'. (n)
\--- com.github.spotbugs:spotbugs-annotations:4.2.0 (n)

javadocElements - javadoc elements for main. (n)
No dependencies

runtimeClasspath - Runtime classpath of source set 'main'.
\--- com.github.spotbugs:spotbugs-annotations:4.2.0
     \--- com.google.code.findbugs:jsr305:3.0.2

runtimeElements - Elements of runtime for main. (n)
No dependencies

runtimeOnly - Runtime only dependencies for source set 'main'. (n)
No dependencies

sourcesElements - sources elements for main. (n)
No dependencies

testAnnotationProcessor - Annotation processors and their dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
+--- com.github.spotbugs:spotbugs-annotations:4.2.0
|    \--- com.google.code.findbugs:jsr305:3.0.2
\--- org.junit.jupiter:junit-jupiter-api:5.6.2
     +--- org.junit:junit-bom:5.6.2
     |    +--- org.junit.jupiter:junit-jupiter-api:5.6.2 (c)
     |    \--- org.junit.platform:junit-platform-commons:1.6.2 (c)
     +--- org.apiguardian:apiguardian-api:1.1.0
     +--- org.opentest4j:opentest4j:1.2.0
     \--- org.junit.platform:junit-platform-commons:1.6.2
          +--- org.junit:junit-bom:5.6.2 (*)
          \--- org.apiguardian:apiguardian-api:1.1.0

testCompileOnly - Compile only dependencies for source set 'test'. (n)
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
\--- org.junit.jupiter:junit-jupiter-api:5.6.2 (n)

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- com.github.spotbugs:spotbugs-annotations:4.2.0
|    \--- com.google.code.findbugs:jsr305:3.0.2
+--- org.junit.jupiter:junit-jupiter-api:5.6.2
|    +--- org.junit:junit-bom:5.6.2
|    |    +--- org.junit.jupiter:junit-jupiter-api:5.6.2 (c)
|    |    +--- org.junit.jupiter:junit-jupiter-engine:5.6.2 (c)
|    |    +--- org.junit.platform:junit-platform-commons:1.6.2 (c)
|    |    \--- org.junit.platform:junit-platform-engine:1.6.2 (c)
|    +--- org.apiguardian:apiguardian-api:1.1.0
|    +--- org.opentest4j:opentest4j:1.2.0
|    \--- org.junit.platform:junit-platform-commons:1.6.2
|         +--- org.junit:junit-bom:5.6.2 (*)
|         \--- org.apiguardian:apiguardian-api:1.1.0
\--- org.junit.jupiter:junit-jupiter-engine:5.6.2
     +--- org.junit:junit-bom:5.6.2 (*)
     +--- org.apiguardian:apiguardian-api:1.1.0
     +--- org.junit.platform:junit-platform-engine:1.6.2
     |    +--- org.junit:junit-bom:5.6.2 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-commons:1.6.2 (*)
     \--- org.junit.jupiter:junit-jupiter-api:5.6.2 (*)

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
\--- org.junit.jupiter:junit-jupiter-engine:5.6.2 (n)

(c) - dependency constraint
(*) - dependencies omitted (listed previously)

(n) - Not resolved (configuration is not meant to be resolved)

A web-based, searchable dependency report is available by adding the --scan option.
== Build Time Summary ==
100% :dumper-api-interface:dependencies (0:00.068)

== BUILD SUCCESSFUL ==

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
```

2) `graphql-java-tools` is using in `dumper-api` module, which is a separate module and I also tried to force `com.graphql-java:graphql-java:15.0` version for all modules:
https://github.com/expatiat/dumper/blob/a7008d873b3caf9ee085cf6dcb87f435cac9c535/build.gradle.kts#L90

3) the error message is `ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.5.3`, here `4.7.2` refers to the version from `com.graphql-java:graphql-java:15.0` dependency, which is used by your plugin (it's a dependency on another classpath - Gradle plugins classpath, it's not the same classpath as what project's module using).

So the question here is, from where `4.5.3` version comes from. Probably any other Gradle module somehow conflicts with `graphql-java-codegen`.

**Comment by kobylynskyi** [comment]
@donbeave you are right, I've checked that bumping graphql-java to 16.x does not resolve the issue you face.

**Comment by donbeave** [comment]
Hi, @kobylynskyi!

I found the reason why I'm getting this error. The error came after I'm adding the Gradle Kotlin JVM plugin.

When I add this to `plugins`:

```kotlin
kotlin("jvm") version "1.4.31" apply false
```

I'm starting to get this error:

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.5.2ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.5.2
FAILURE: Build failed with an exception.
```

I have tried with the latest Kotlin plugin and it works fine, no exception:

```kotlin
kotlin("jvm") version "1.5.0-M2" apply false
```

**Comment by kobylynskyi** [comment]
@donbeave thanks for the update.
Glad you found the root cause

**Comment by clouddra** [comment]
Hi @donbeave, I am also seeing this error. I am not using kotlin so i doubt it has anything to do with the kotlin plugin.

**Comment by donbeave** [comment]
@clouddra maybe you have the Apollo Gradle plugin? It can be another Gradle plugin that also uses ANTLR Tool, I found Kotlin and Apollo plugins are using it.

**Comment by clouddra** [comment]
> @clouddra maybe you have the Apollo Gradle plugin? It can be another Gradle plugin that also uses ANTLR Tool, I found Kotlin and Apollo plugins are using it.

Yes that was what i found yesterday. I think the 5.0.0 release should fix it since Apollo ANTLR is on a later version
